### ISSUE TITLE
[BUG] Previews not working on firefox

### ISSUE THREAD

**Issue by tefkah** [hauptrolle/chakra-templates#139] opened 2021-11-17 14:25 UTC
Thanks for the fantastic website and templates!

However, the previews don't seem to work for me in Firefox.
## Page

In Firefox:
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/21983833/142218335-aca2223a-15eb-4a3c-abb9-e300f89897ab.png">

In Brave:

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/21983833/142218652-ae122138-872f-487e-b7e8-35e7b1c245dd.png">

## Network:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21983833/142218147-d7dd2e8f-2248-441e-859c-7079bf981eda.png">

## Info

No specific tracker blocking or anything that would normally break these kinds of things.

MacBook Air M1, MacOS Monterey, Firefox 94.0.1

**Comment by hauptrolle** [comment] 2021-12-14 15:53
This is probably the same issue as #128. Will have a look at it, and maybe finally refactor the preview frame to use https://github.com/codesandbox/sandpack :)

**Comment by populationtwo** [comment] 2021-12-15 14:37
This appears to be caused by [Enhanced Tracking Protection](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop) on Firefox. The preview frame works fine if ETP is disabled.

@hauptrolle  I can look into refactoring to Sandpack if you'd like to go that route.

**Comment by hauptrolle** [comment] 2021-12-15 14:59
Hey @populationtwo I have the problem now in Chrome too...
But yes, I think we should go the way, and try out sandpack. We can have a chat about that on the discord 👍

**Comment by rvalle** [comment] 2022-01-10 14:04
I am locked out of chakra templates... not working on any of my browsers. Also getting grey boxes.

**Comment by NSDrowned** [comment] 2022-01-22 22:53
Same here... gray boxes in Chrome

**Comment by dbruvers** [comment] 2022-03-24 14:35
The previews do work if you click the "Open in Fullscreen" button
![open in fullscreen](https://user-images.githubusercontent.com/15773882/159939941-630b3b81-9c23-4450-981a-eacf77c6f45f.png)

**Comment by henrychea** [comment] 2022-04-07 10:19
Can concur, not working in Chrome as well.

macOS 12.3.1 , Chrome Version 100.0.4896.75 (Official Build) (x86_64)

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/40254517/162177608-52dc055e-a8df-4c0d-b948-d1cc683ed928.png">

**Comment by statico** [comment] 2022-04-08 05:13
I tried running this project locally and can't get them to show up in Firefox or Chrome either.

**Comment by henrychea** [comment] 2022-05-03 03:37
Update with some info from Firefox dev tools `The resource from “https://fonts.googleapis.com/css?family=” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).` Maybe this can help.

**Comment by henrychea** [comment] 2022-05-05 08:37
This seems to be an issue with the Google Font's Api. Maybe someone could submit a pull request to update the font link and all the bugs should go away.

```Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
chakra-templates.dev/:1 Refused to apply style from 'https://fonts.googleapis.com/css?family=' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
chakra-templates.dev/:1 Refused to apply style from 'https://fonts.googleapis.com/css?family=' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
callToActionWithIllustration:1 Refused to apply style from 'https://fonts.googleapis.com/css?family=' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
splitScreen:1 Refused to apply style from 'https://fonts.googleapis.com/css?family=' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
callToActionWithVideo:1 Refused to apply style from 'https://fonts.googleapis.com/css?family=' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
callToActionWithAnnotation:1 Refused to apply style from 'https://fonts.googleapis.com/css?family=' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
withBackgroundImage:1 Refused to apply style from 'https://fonts.googleapis.com/css?family=' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Comment by henrychea** [comment] 2022-10-02 10:49
I have an update for all Firefox users, you can get the preview to work by clicking any link that goes to an external site (use the contribute link in the navbar). Then just navigate back and the preview works.

**Comment by hauptrolle** [comment] 2022-10-22 08:54
closed in favor if #198

**Closed by hauptrolle** 2022-10-22 08:54 UTC
